"""Stage only referenced public assets and generate Netlify security headers.

Run from any directory with Python 3. No packages or network access required.
"""
import base64
import hashlib
import json
import re
import shutil
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'dist'
MARKER = OUTPUT / '.tara-generated'


class Page(HTMLParser):
    def __init__(self, html):
        super().__init__(convert_charrefs=True)
        self.assets = set()
        self.scripts = []
        self.feed(html)

    def handle_starttag(self, tag, attributes):
        attrs = dict(attributes)
        if any(name.startswith('on') for name in attrs):
            raise ValueError('Inline event attributes are prohibited by CSP')
        if tag == 'script' and 'src' in attrs:
            self.scripts.append(attrs)
        if tag in ('img', 'video', 'source', 'script') or (tag == 'link' and attrs.get('as') == 'image'):
            for name in ('src', 'data-src', 'poster', 'data-poster', 'href'):
                if attrs.get(name):
                    self.assets.add(attrs[name])
            for name in ('srcset', 'data-srcset', 'imagesrcset'):
                for candidate in attrs.get(name, '').split(','):
                    if candidate.strip():
                        self.assets.add(candidate.strip().split()[0])


def build():
    html = (ROOT / 'index.html').read_text()
    page = Page(html)
    lock = {entry['file']: entry for entry in json.loads((ROOT / 'tools/vendor-lock.json').read_text())}
    for script in page.scripts:
        entry = lock[script['src']]
        data = (ROOT / script['src']).read_bytes()
        integrity = 'sha384-' + base64.b64encode(hashlib.sha384(data).digest()).decode()
        if hashlib.sha256(data).hexdigest() != entry['sha256'] or integrity != entry['integrity'] or integrity != script.get('integrity'):
            raise ValueError('Vendor integrity mismatch: ' + script['src'])

    for name in page.assets:
        path = Path(name)
        if path.is_absolute() or '..' in path.parts or path.parts[0] not in ('images', 'images2', 'media', 'assets'):
            raise ValueError('Unexpected public asset: ' + name)
        if any(part.startswith('.') for part in path.parts) or path.suffix.lower() not in ('.png', '.jpg', '.jpeg', '.webp', '.mp4', '.js'):
            raise ValueError('Unexpected public file type: ' + name)
        source = ROOT / path
        if not source.is_file() or source.resolve() != source.absolute():
            raise ValueError('Missing asset or symlink: ' + name)

    if OUTPUT.exists():
        if OUTPUT.is_symlink() or not MARKER.is_file():
            raise ValueError('Refusing to replace an unrecognized dist directory')
        shutil.rmtree(OUTPUT)
    OUTPUT.mkdir()
    MARKER.write_text('Generated by tools/build_site.py; safe to rebuild.\n')
    # Only the generated deployment uses content-addressed media URLs. Source
    # artwork, responsive variants and video bytes remain completely unchanged.
    media_names = {}
    for name in sorted(page.assets):
        path = Path(name)
        if path.suffix.lower() != '.js':
            digest = hashlib.sha256((ROOT / name).read_bytes()).hexdigest()[:20]
            media_names[name] = path.with_name(path.stem + '.' + digest + path.suffix).as_posix()
    for name in sorted(media_names, key=len, reverse=True):
        html = html.replace(name, media_names[name])
    (OUTPUT / 'index.html').write_text(html)
    for name in sorted(page.assets):
        target = OUTPUT / media_names.get(name, name)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(ROOT / name, target)

    inline_scripts = re.findall(r'<script\s*>([\s\S]*?)</script>', html)
    hashes = ["'sha256-" + base64.b64encode(hashlib.sha256(script.encode()).digest()).decode() + "'" for script in inline_scripts]
    csp = '; '.join([
        "default-src 'self'", "base-uri 'none'", "object-src 'none'",
        "frame-ancestors 'none'", "frame-src 'none'", "form-action 'none'",
        "script-src 'self' " + ' '.join(hashes), "script-src-attr 'none'",
        # Existing Tailwind runtime generates styles; GSAP and markup use inline styles.
        "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
        "font-src 'self' https://fonts.gstatic.com", "img-src 'self'",
        "media-src 'self'", "connect-src 'none'", "worker-src 'none'",
        "manifest-src 'none'", 'upgrade-insecure-requests'
    ])
    headers = {
        'Content-Security-Policy': csp,
        'X-Content-Type-Options': 'nosniff',
        'Referrer-Policy': 'strict-origin-when-cross-origin',
        'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=(), bluetooth=(), accelerometer=(), gyroscope=(), magnetometer=(), autoplay=(self), fullscreen=(self)',
        'Cross-Origin-Opener-Policy': 'same-origin',
        'Cross-Origin-Resource-Policy': 'same-origin',
        'Strict-Transport-Security': 'max-age=31536000',
    }
    lines = ['/*'] + ['  ' + key + ': ' + value for key, value in headers.items()]
    # Avoid overlapping Cache-Control declarations: Netlify can combine values.
    for route in ('/', '/index.html'):
        lines += ['', route, '  Cache-Control: public, max-age=0, must-revalidate']
    # Every published media filename above includes its content digest.
    for route in ('/images/*', '/images2/*', '/media/*'):
        lines += ['', route, '  Cache-Control: public, max-age=31536000, immutable']
    for script in page.scripts:
        lines += ['', '/' + script['src'], '  Cache-Control: public, max-age=31536000, immutable']
    (OUTPUT / '_headers').write_text('\n'.join(lines) + '\n')
    print('Built dist with', len(page.assets), 'referenced assets; vendor integrity and CSP hashes verified.')


if __name__ == '__main__':
    build()
